server:
  port: 8082

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://localhost:9411/zipkin/

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/java_api
      username: postgres
      password: root
      driverClassName: org.postgresql.Driver